version: '3.7'
services: 
  router_bypass:
    image: elespejo/bypass-${ARCH}:${BYPASS_VERSION}
    restart: always

    network_mode: 'host'
    
    cap_add: 
      - 'NET_ADMIN'

    environment: 
      - LAN=${LAN}
      - BASE_PORT=${BASE_PORT}
      - BALANCE_NUM=${BALANCE_NUM}

    volumes: 
      - type: bind
        source: ${BYPASS_CONFIG}
        target: /bypass

    stdin_open: true